### PR TITLE
Heartbeat3

### PR DESCRIPTION
**Pull request by TobiasHuberAt**
Third try to
add heartbeat to SubscriptionResponse
created V2.2 for http services which use subscriptions
-> discussion on https://forum.vdv.de/viewtopic.php?f=63&t=188&p=569#p569
-> Protokoll IBIS-IP Telco 28.11.2018

I splitted the change into two commits, in order to make the change more visible
1st commit: create and use v2.2
2nd commit: change the structs

@BerndSchubert:
in consideration of https://forum.vdv.de/viewtopic.php?f=63&t=188&p=569#p595
1.  I changed to type IBIS-IP.duration
2,3,4: please note my comment in forum

@ReneFischli:
in consideration of https://forum.vdv.de/viewtopic.php?f=63&t=188&p=569#p597
- added  minOccurs="0" to Active

### CODE REVIEW

**Comment by sledz** [comment]
@BerndSchubert, @renefischli, @pschuessler, @Torsten-Franke, waiting for your comments and/or approvals.

**Comment by pschuessler** [comment]
We accept the proposal and have no objections.

**Comment by renefischli** [comment]
Ok for us , Sorry for the late response.

**Comment by BerndSchubert** [comment]
As a result of continued discussion further changes were made to file "IBIS-IP_common_V2.2.xsd". This pull-request is no longer up-to-date. It will be renewed after finish of discussion in IBIS-IP working group.

**Pull request closed without merging**
