### PR TITLE
Release of Version 2.1

### PR DESCRIPTION
**Pull request by BerndSchubert**
XSD file pool for IBIS-IP version 2.1 is in final state after finishing discussion within VDV 301 working group

### CODE REVIEW

**Comment by BerndSchubert** [comment]
On its telco dated October 31st 2018 the VDV 301 working group decided to use GitHub productively for further development of XSD file pool. Release of IBIS-IP version 2.1 was decided too.

**Comment by renefischli** [comment]
pull request approved

**Comment by Torsten-Franke** [comment]
pull request approved by IVU

**Comment by pschuessler** [comment]
Pull request approved by DResearch Fahrzeugelektronik GmbH.
Thank you for your effort!

**Pull request merged**
